### ISSUE TITLE
init fail

### ISSUE THREAD

**Issue by yuwenhua** [beylsp/proxy-toggle#1]
C:\>pip install --upgrade GnuPG
Requirement already up-to-date: GnuPG in c:\python27\lib\site-packages
Requirement already up-to-date: psutil>=1.2.1 in c:\python27\lib\site-packages (
from GnuPG)

C:\>px --init
Please enter proxy host: a
Please enter proxy user: b
Please enter proxy password:
Error initializing keyring.
GnuPG is not installed!
Traceback (most recent call last):
  File "C:\Python27\Scripts\px-script.py", line 9, in <module>
    load_entry_point('proxy-toggle==1.0.5', 'console_scripts', 'px')()
  File "C:\Python27\lib\site-packages\proxytoggle\px.py", line 367, in main
    init_proxy_store(config.renew)
  File "C:\Python27\lib\site-packages\proxytoggle\px.py", line 52, in __init__
    self._init_app()
  File "C:\Python27\lib\site-packages\proxytoggle\px.py", line 76, in _init_app
    sys.exit(err.errno)
AttributeError: 'exceptions.RuntimeError' object has no attribute 'errno'

**Comment by beylsp** [comment]
Fixed: `SystemExit` is now raised with error message when `RuntimeError` occurs as it doesn't have errno attribute.

Be aware that proxy-toggle uses `gnupg` binary and thus must be accessible on your platform. Documentation is updated accordingly.
